[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.63.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/wedding"
  to = "https://youtu.be/YeeFQgooIQM"

[[redirects]]
  from = "/married"
  to = "https://photos.app.goo.gl/4pFEECzTwsucv3KWA"

[[redirects]]
  from = "/.well_known/*"
  to = "/well_known/:splat"
  status = 200
  force = true
